### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by GoogleCodeExporter** [threerings/openvpn-auth-ldap#33]
```
What steps will reproduce the problem?
1. Installing openvpn-auth-ldap from most distros installs version 2.0.3, which 
was built in 2008.


What is the expected output? What do you see instead?
Much development has happened since 2008, (including working ldaps and STARTTLS 
support) and it would be great to not have to compile to use the plugin.

Thanks!

```

Original issue reported on code.google.com by `ch...@pentandra.com` on 18 Oct 2013 at 7:27

**Comment by mkhon** [comment]
Can we have a new release? I'd be glad to have it for #7

**Comment by k0ste** [comment]
@samskivert can you bump a release? Since last release passed 12 years, releases is important for packagers.
From 2.0.3 openvpn-auth-ldap was get RFC2307 groups support, challenge-response protocol and builds with last versions of OpenVPN with modern GCC's.
Thanks.

**Comment by samskivert** [comment]
Done.
