### ISSUE TITLE
Authenticate non local users to OpenVPN with openvpn and openvpn-auth-ldap.

### ISSUE THREAD

**Issue by Zuboram** [threerings/openvpn-auth-ldap#70]
Hi, does this works to authenticate non local users?

I'm trying to authenticate users that belongs to a Jumpcloud account through ldap, in others words users that doesn't exist locally in the openvpn server... is this possible? or am I just wasting my time? I really want to avoid the commercial option in AWS + OpenVPN to authenticate JumpCloud users which is also done with ldap.

Regards

**Comment by k0ste** [comment]
@Zuboram 
This module definitely to auth non local users.

**Comment by Zuboram** [comment]
@k0ste yes it is, my bad. Apparently the issue was with the client OpenVPN Connect on Windows 10. It seem this client forces the client.ovpn to always have a client cert and key and it is always throwing the error "core error missing external pki alias". 
I have an openvpn server with client-cert-not-required and with the community client, the OpenVPN GUI ,seems to work fine.

Has anyone been able to authenticate with the OpenVPN Connect client on Windows 10 without client certs?

**Comment by k0ste** [comment]
@Zuboram 
Your client should have option `auth-user-pass`, and server should be runned with `verify-client-cert none`.

**Comment by Zuboram** [comment]
@k0ste I will test it with that configuration tomorrow, hope that is all what it need. Thanks!

**Comment by Zuboram** [comment]
Nope, that didn't work...it keeps giving me the error "core exception: connect error: missing external pki alias"
I'm using an openvpn server v2.4.7 in Ubuntu 16.04 and trying to connect to it with the OpenVPN Connect version 2.7.1.101 on Windows 10.
The connection works if I use the OpenVPN GUI v11.13.0.0 client.
